//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWaterWeb {
    
    
    public partial class index {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// TopNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.TopNews TopNews1;
        
        /// <summary>
        /// BaseUserCtrl11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl11;
        
        /// <summary>
        /// BaseUserCtrl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl2;
        
        /// <summary>
        /// BaseUserCtrl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl3;
        
        /// <summary>
        /// BaseUserCtrl4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl4;
        
        /// <summary>
        /// BaseUserCtrl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl1;
        
        /// <summary>
        /// BaseUserCtrl5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl5;
        
        /// <summary>
        /// BaseUserCtrl6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl6;
        
        /// <summary>
        /// BaseUserCtrl7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl7;
        
        /// <summary>
        /// BaseUserCtrl8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl8;
        
        /// <summary>
        /// BaseUserCtrl10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl10;
        
        /// <summary>
        /// BaseUserCtrl9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.BaseUserCtrl BaseUserCtrl9;
        
        /// <summary>
        /// ChildSiteUserCtrl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.ChildSiteUserCtrl ChildSiteUserCtrl1;
        
        /// <summary>
        /// LinkSite1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewWaterWeb.UserCtrl.LinkSite LinkSite1;
    }
}
